AWSTemplateFormatVersion: 2010-09-09
Description: "cloudformation template to create CUR"

Parameters: 
  ReportName:
    Type: String
    Default: nopsbilling-daily-gzip
    Description: nOps daily generated report name.

  s3prefix:
    Type: String
    Default: something
    Description: nOps daily generated reports folder prefix.

  BucketName:
    Type: String
    Default: nopsbucketforlogs
    Description: s3 bucket name for nOps daily reports.


Resources:
  nopsBucketForLogs:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub '${BucketName}-${AWS::AccountId}'


  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref nopsBucketForLogs
      PolicyDocument:
        Version: 2012-10-17
        Id : 'Policy1335892530063'
        Statement:
          - Action:
              - 's3:GetBucketAcl'
              - 's3:GetBucketPolicy'
            Effect: Allow
            Sid: 'Stmt1335892150622'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref nopsBucketForLogs
            Principal: 
              Service: 'billingreports.amazonaws.com'


          - Action:
              - 's3:PutObject'
            Effect: Allow
            Sid: 'Stmt1335892526596'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref nopsBucketForLogs
                - /*
            Principal: 
              Service: 'billingreports.amazonaws.com'


  nopsReportDefinition:
    Type: AWS::CUR::ReportDefinition
    DependsOn: 
      - nopsBucketForLogs
      - BucketPolicy
    Properties: 
      AdditionalArtifacts: 
        - "REDSHIFT"
        - "QUICKSIGHT"
      AdditionalSchemaElements: 
        - "RESOURCES"
      Compression: "GZIP"
      RefreshClosedReports: true
      Format: "textORcsv"
      ReportName: !Ref ReportName
      ReportVersioning: "OVERWRITE_REPORT"
      S3Bucket: !Ref nopsBucketForLogs
      S3Prefix: !Ref s3prefix
      S3Region: !Sub '${AWS::Region}'
      TimeUnit: "DAILY"
